# Generated by Django 5.0 on 2024-01-03 18:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('allowance_name', models.CharField(max_length=200)),
                ('is_taxable', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('deduction_name', models.CharField(max_length=200)),
                ('is_taxable', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=200)),
                ('department_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position_name', models.CharField(max_length=200)),
                ('position_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('initial_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('birthday', models.DateField(blank=True, help_text="Employee's birthday", null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=500, null=True)),
                ('date_hired', models.DateField(blank=True, help_text="Employee's date hired", null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.position')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_currency', models.CharField(blank=True, choices=[('etb', 'ETB'), ('usd', 'USD')], max_length=200, null=True)),
                ('allowance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.allowance')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_allowances', to='hst_payroll_manager.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_currency', models.CharField(blank=True, choices=[('etb', 'ETB'), ('usd', 'USD')], max_length=200, null=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hst_payroll_manager.deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hst_payroll_manager.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePercentageDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_percentage', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hst_payroll_manager.deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hst_payroll_manager.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('total_gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pension_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total_working_days', models.IntegerField(blank=True, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('payment_currency', models.CharField(blank=True, choices=[('etb', 'ETB'), ('usd', 'USD')], max_length=200, null=True)),
                ('foreign_currency_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pension', models.DecimalField(decimal_places=1, default=7, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pension %')),
                ('pension_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Pension contribution of the employee in amount')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.employee')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
            },
        ),
    ]
