# Generated by Django 5.0 on 2023-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0002_position_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'In Active')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, help_text="Employee's birthday", null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(blank=True, help_text="Employee's date hired", null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'In Active')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'In Active')], max_length=200, null=True),
        ),
    ]
