# Generated by Django 5.0 on 2023-12-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0003_alter_department_status_alter_employee_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_currency', models.CharField(blank=True, choices=[('etb', 'ETB'), ('usd', 'USD')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.paymentcurrency'),
        ),
    ]
