# Generated by Django 5.0 on 2023-12-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0004_paymentcurrency_employee_payment_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcurrency',
            options={'verbose_name_plural': 'Payment Currencies'},
        ),
    ]
