# Generated by Django 5.0 on 2023-12-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0006_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Taxes'},
        ),
    ]
