# Generated by Django 5.0 on 2023-12-25 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0007_alter_tax_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
