# Generated by Django 5.0 on 2023-12-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0009_alter_tax_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payment_currency',
        ),
    ]
