# Generated by Django 5.0 on 2023-12-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0010_remove_employee_monthly_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_days', models.IntegerField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('transport_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('housing_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overtime_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('medical_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('annual_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('foreign_currency_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('performance_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('one_time_signing_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('car_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuel_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mobile_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('school_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('holiday_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('credit_association_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pension_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('edir_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('red_cross_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('social_welfare_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('loan_deduction_short_term', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('loan_deduction_long_term', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('provident_fund_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.employee')),
                ('payment_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hst_payroll_manager.paymentcurrency')),
            ],
        ),
    ]
