# Generated by Django 5.0 on 2023-12-26 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0011_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='monthly_salary',
            new_name='gross_salary',
        ),
        migrations.AddField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='red_cross_contribution',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
