# Generated by Django 5.0 on 2023-12-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0014_position_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
    ]
