# Generated by Django 5.0 on 2023-12-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0016_employee_account_number_employee_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
