# Generated by Django 5.0 on 2023-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0018_alter_department_status_alter_employee_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='payment_currency',
            field=models.CharField(blank=True, choices=[('etb', 'ETB'), ('usd', 'USD')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentCurrency',
        ),
    ]
