# Generated by Django 5.0 on 2023-12-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0020_alter_salary_annual_bonus_alter_salary_car_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='final_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='initial_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
