# Generated by Django 5.0 on 2023-12-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0022_alter_salary_annual_bonus_alter_salary_car_allowance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='pension_contribution',
        ),
    ]
