# Generated by Django 5.0 on 2023-12-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0023_remove_salary_net_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
