# Generated by Django 5.0 on 2023-12-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0024_salary_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='The total tax, inclusive of taxable benefits.'),
        ),
    ]
