# Generated by Django 5.0 on 2023-12-27 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_payroll_manager', '0026_alter_salary_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='tax',
        ),
        migrations.AddField(
            model_name='salary',
            name='pension',
            field=models.DecimalField(decimal_places=1, default=7, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='salary',
            name='pension_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
